id: A808A89AB
base_file: f11E1.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:00:14.705840
  last_modified_at: 2022-05-31 05:00:14.705867
